### ISSUE TITLE
How to onboard multiple subscription which is present in the same tenant in azure lighthouse ?

### ISSUE THREAD

**Issue by ajaywayal2** [Azure/Azure-Lighthouse-samples#101]
Trying to onboard multiple subscription which is present in the same tenant in azure light house. Not able to find such ARM template.

**Comment by decker78** [comment]
I'm looking for the same. I however don't see a way to feed the templed an array with subscriptions. Tried with a main template in tenant scoped and linked template for lighthouse delegation, bit there is no way to loop through an array setting the subscriptionid for that linked deployment

**Comment by azurenative** [comment]
i dont know if you are using azure pipelines, but i have used that to deploy the arm template to multiple subscriptions.
here is a reference link : https://adatum.no/azure/multi-subscription-deployment-with-devops-and-azure-lighthouse

**Comment by decker78** [comment]
Thanks for the reference. But I'm looking to enable customers (without an azure pipeline) to onboard multiple subscriptions using one template instead of having them to run the template once for each subscription. But that seems not possible.

**Comment by decker78** [comment]
Ah this just works when starting with a tenant deployment and use a linked template for the delegation using a copy loop in the subscriptionid

**Comment by serenaz** [comment]
Glad you found a solution!
