### ISSUE TITLE
Add Get-AzDelegatedSubscription to lighthouse-demo

### ISSUE THREAD

**Issue by whaakman** [Azure/Azure-Lighthouse-samples#29]
Suggestion: The demo would work better (personal opinion) when you include the function as you build here: https://github.com/Azure/Azure-Lighthouse-samples/blob/master/Azure-Delegated-Resource-Management/tools/get-azdelegatedsubscription/Get-AzDelegatedSubscription.ps1

As the demo script here: https://github.com/Azure/Azure-Lighthouse-samples/tree/master/Azure-Delegated-Resource-Management/tools/lighthouse-demo will run on all subscriptions that one would have access too ($subs = get-azsubscription), not just the ones added through delegated resource management. 

Just an idea :) but awesome examples!

**Comment by krnese** [comment]
Thanks for the suggestion!
Will incorporate and make an update.
