### ISSUE TITLE
Error deploying rgDelegatedResourceManagement (Code: InvalidRegistrationDefinitionUri)

### ISSUE THREAD

**Issue by GPetrites** [Azure/Azure-Lighthouse-samples#31]
I'm trying to deploy rgDelegatedResourceManagement using the supplied template and parameter files.

Powershell command:

New-AzResourceGroupDeployment -ResourceGroupName LighthouseTest -TemplateFile .\rgDelegatedResourceManagement.json -TemplateParameterFile .\rgDelegatedResourceManagement.parameters.json

Raw error:
(Subscription id in error is masked by me but matches the target subscription for the deployment)

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"error\": {\r\n    \"code\": \"InvalidRegistrationDefinitionUri\",\r\n    \"message\": \"The registration definition request scope '/subscriptions/99999999-9999-9999-9999-999999999999/resourcegroups/LighthouseTest' should be '/subscriptions/&lt;subscriptionId&gt;'.\"\r\n  }\r\n}"
    }
  ]
}

Parameter file:
(Tenant id and principal id are masked by me below but match the Azure AD tenant id and security group ids for the Azure AD and security group which is requesting delegated permissions)

{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "mspName": {
            "value": "Breakpoint Technology"
        },
        "rgName": {
            "value": "LighthouseTest"
        },
        "mspOfferDescription": {
            "value": "Breakpoint Technology - AI Analysis"
        },
        "managedByTenantId": {
            "value": "11111111-1111-1111-1111-111111111111"
        },
        "authorizations": {
            "value": [
                {
                    "principalId": "22222222-2222-2222-2222-222222222222",
                    "principalIdDisplayName": "Lighthouse Test",
                    "roleDefinitionId": "73c42c96-874c-492b-b04d-ab87d138a893"
                }
            ]
        }
    }
}

I have confirmed the target subscription has the Microsoft.ManagedServices provider registered.

**Comment by krnese** [comment]
You are trying to deploy the template to a resource group, but it can only be deployed to a subscription. You must use New-AzDeployment

**Comment by GPetrites** [comment]
Good catch.  That resolved it.  Thanks.
