### ISSUE TITLE
Incorrect template delegatedResourceManagement.json

### ISSUE THREAD

**Issue by pachi-belero** [Azure/Azure-Lighthouse-samples#33]
I think the sample template "Azure-Delegated-Resource-Management/templates/delegated-resource-management/delegatedResourceManagement.json" makes use of an inexistent parameter "mspName". Al least the deployment failed for me as it is, and it worked when I added the parameter...
In fact, I used a subscriptionName parameter instead, to be consistent with the sample templates for resource groups (but I'm not sure if this was the intent, or if this value finally shows up somewhere)

**Comment by mboback-spg** [comment]
pachi-belero what was the modified file you used to fix this issue with the subscriptionName parameter? I'm having the same issue/error with the missing mspName parameter.

**Comment by ctolkien** [comment]
Same issue here, `mspName` is not one of the parameters.

**Comment by simkjels** [comment]
I believe the template and parameter file was updated to replace mspName with mspOfferName to make the parameter more descriptive. Make sure you are consistent with these two parameters across your parameter file and template file.

**Comment by ctolkien** [comment]
`mspName` is still referenced in the template, hence the issue.

**Comment by krnese** [comment]
Thanks all. The variable that referenced the "mspName" parameter that no longer exists, has been updated.

Can you give it a try and let me know if there's any issues?

**Comment by pachi-belero** [comment]
Seems OK to me now, thanks. The samples for resource groups in [rg-delegated-resource-management folder](https://github.com/Azure/Azure-Lighthouse-samples/tree/master/Azure-Delegated-Resource-Management/templates/rg-delegated-resource-management) still seem to use a different criteria for naming the `Microsoft.ManagedServices/registrationAssignments` resource, though, but I'm not sure what is the intent there so I guess it is OK ayway.

**Comment by krnese** [comment]
Great to hear.
The registrationAssignment name must be unique at scope, hence the rg registrationAssignment is using the rg name to construct the deterministic guid in this case.

**Comment by pachi-belero** [comment]
Great, thanks. I think the issue can be closed then when you want
