### ISSUE TITLE
InsufficientPrivilegesForManagedServiceResource

### ISSUE THREAD

**Issue by jpendyala** [Azure/Azure-Lighthouse-samples#39]
I get "InsufficientPrivilegesForManagedServiceResource" error when I run the template. Is linking partner ID a mandatory step? Can I deploy the template without a partner ID?

**Comment by krnese** [comment]
Can you point me to the template you are deploying? 
From an RBAC perspective, we require the customer (who onboard) to be Owner.

**Comment by jpendyala** [comment]
Thanks for a quick reply @krnese 

This is the template I'm using:
https://github.com/Azure/Azure-Lighthouse-samples/blob/master/Azure-Delegated-Resource-Management/templates/delegated-resource-management/delegatedResourceManagement.json

**Comment by krnese** [comment]
And you are:
1) Deploying this as a user in the customer tenant?
2) The user has Owner permission at the subscription?
3) You deploy it as a subscription level template (New-AzDeployment / az deployment create)?

**Comment by jpendyala** [comment]
I'm deploying it in the customer tenant using New-AzDeployment. I'm the GA in the customer tenant and owner on the subscription. 

I created a TemplateParameterFile by including my Principal ID and Reader Role Def ID in the authorizations section of the file.

**Comment by krnese** [comment]
Are you deploying it as a guest account, or a user belonging to the customer AAD?
Can you pls deploy it as a user originating from the customer AAD with Owner permission at scope?

**Comment by jpendyala** [comment]
I followed the Powershell steps mentioned in this document
https://docs.microsoft.com/en-us/azure/lighthouse/how-to/onboard-customer

I'm a user in customer AAD and I have owner permission at the subscription

**Comment by krnese** [comment]
Thanks. Can you please open a support ticket so we can investigate further?

**Comment by dorankerkhofs** [comment]
I experienced exactly the same issue. 

i was connect with azure ad only (connect-azureAD).
When i connected to the azure account it worked (Connect-AzAccount).

Good Luck!

**Comment by jpendyala** [comment]
Let me try that 
Thanks @dorankerkhofs

**Comment by krnese** [comment]
Did it work?
