### ISSUE TITLE
ClassicAdministratorListFailed

### ISSUE THREAD

**Issue by TerminallyChilI** [Azure/Azure-Lighthouse-samples#40]
Hi There,

I'm trying to deploy the ARM template "delegatedResourceManagement"  to a customers subscription.

The account being used to deploy has Contributor permission to the subscription I'd like to deploy into.

My subscription is provided via a CSP (Cloud Service Provider)

I have found that on the Access Control page of the subscription, under the "Classic Administrators" section that there is the following advisory message:
"This type of subscription does not support classic administrators."

There are no classic administrators listed.

Please see the full error below:
New-AzDeployment : 8:12:23 PM - Resource Microsoft.ManagedServices/registrationDefinitions 'c62a69fe-8c56-57fc-8f1a-8be43d413609' failed with message '{
  "error": {
    "code": "ClassicAdministratorListFailed",
    "message": "Failed to list classic administrators of subscription 'dec6084b-c0eb-43d3-95e2-8a07f1bd2c68': 'The subscription ID was not found.'."
  }
}'

Is this template dependent on being classic administrator supported?
Is there any workaround to this issues?

Please let me know if you would like me to provide any additional information and I would be more than happy to provide.

![image](https://user-images.githubusercontent.com/25244283/66470208-df30e280-ead4-11e9-9f7f-aef223d40027.png)

![image](https://user-images.githubusercontent.com/25244283/66470309-10111780-ead5-11e9-9749-cf7a85aadc66.png)

**Comment by krnese** [comment]
For a customer tenant to onboard to Lighthouse, the deployment must be submitted by a customer user with Owner permission at the subscription scope.
Can you ensure this is in place and try the deployment again?

**Comment by TerminallyChilI** [comment]
Thanks for your prompt reply, and for confirming that Kristian.

I think this will be the cause as we don't have Owner permission on the subscription, I will contact the CSP to see if the Owner permissions can be organised and report back.

**Comment by krnese** [comment]
Thanks. Closing the issue for now. Pls re-open if still running into issues when being Owner.

**Comment by allruiz** [comment]
I'm having the same issue, even when the docs say that a user with the Admin Agent Role can perform the operation:

"If the subscription was created through the Cloud Solution Provider (CSP) program, any user who has the Admin Agent role in your service provider tenant can perform the deployment." https://docs.microsoft.com/en-us/azure/lighthouse/how-to/onboard-customer#deploy-the-azure-resource-manager-template

```
{
  "code": "InvalidTemplateDeployment",
  "details": [
    {
      "code": "InvalidManagedServicesTemplateDeployment",
      "message": "The managed services template deployment file contains invalid values. Please see details.",
      "details": [
        {
          "code": "ClassicAdministratorListFailed",
          "message": "Failed to list classic administrators of subscription 'x-x-x-x': 'The subscription ID was not found.'."
        }
      ]
    }
  ],
  "message": "The template deployment 'Microsoft.Template-20220804102251' is not valid according to the validation procedure. The tracking id is 'e28b67b5-c186-47c0-a32b-6c3cd760cc1e'. See inner errors for details."
}
```
