### ISSUE TITLE
Set delegated Service Provider role

### ISSUE THREAD

**Issue by cwester72** [Azure/Azure-Lighthouse-samples#50]
Is there a way to give the owner role (Not contributer role) to a managed service provider?

**Comment by krnese** [comment]
Owner is currently not supported via Lighthouse delegation, but something we are looking into.
Can you elaborate a bit on the use case(s) for why Owner would be required/preferred?

**Comment by cwester72** [comment]
We would like owner to help manage RBAC roles to the subscription for the customer as they wouldn’t know what roles would be needed to delegate access to their own employees.


[360 Visibility]<https://www.360visibility.com/?source=sig>
Craig Wester
Cloud Solutions Consultant
cwester@360visibility.com<mailto:cwester@360visibility.com> | (905) 907-3614<tel:(905)%20907-3614>
926 Nashville Rd., Vaughan ON L0J 1C0
[Twitter]<https://twitter.com/360visibility>[LinkedIn]<https://www.linkedin.com/company/360-visibility>[YouTube]<https://www.youtube.com/user/360visibilityinc>[Facebook]<https://www.facebook.com/360Vis/>[Instagram]<https://www.instagram.com/360_visibility/>
www.360visibility.com<https://www.360visibility.com/?source=sig>
[Get Jet Global Unlimited Viewer Users before December 27. Unlimited Viewer Users will be discontinued after this date.]<https://insightsoftware.com/promos/jet/q4-2019/?utm_source=360visibility.com&utm_medium=partner>
Holiday Hours
Open: December 24 & December 31 from 9am - 1pm
Closed: December 25 - 27 & January 1
If you have an urgent support matter, please open a ticket with the related department or visit 360 Visibility Support<https://www.360visibility.com/support/>
Happy Holidays from 360 Visibility!

**Comment by krnese** [comment]
Thanks. Closing this as we are actively investigating this on our side.
