### ISSUE TITLE
Azure Functions not accessible with contributor role

### ISSUE THREAD

**Issue by lcarli** [Azure/Azure-Lighthouse-samples#55]
I just create a Resource Group delegate access to my client resource group with Contributor Role.
We can access everything but Function Apps. I can even access the storage account of my function.

The error message is:

![image](https://user-images.githubusercontent.com/4472823/77919279-f58d4f00-726a-11ea-93f6-9eeba812d726.png)

I'm using this template to do it:

[rg-delegated-resource-management](https://github.com/Azure/Azure-Lighthouse-samples/tree/master/Azure-Delegated-Resource-Management/templates/rg-delegated-resource-management)

**Comment by lcarli** [comment]
Any news???

**Comment by serenaz** [comment]
Hey! Azure Lighthouse doesn't support roles with DataActions https://docs.microsoft.com/en-us/azure/lighthouse/concepts/cross-tenant-management-experience#current-limitations
