### ISSUE TITLE
Template file to onboard subscription is invalid

### ISSUE THREAD

**Issue by hakashya** [Azure/Azure-Lighthouse-samples#81]
The template defined here: https://github.com/Azure/Azure-Lighthouse-samples/blob/master/templates/delegated-resource-management/delegatedResourceManagement.json to onboard subscriptions has an extra field in the template outputs section, called delegatedRoleDefinitionIds. Presence of this field makes the template invalid, and the template cannot be deployed. 

This incorrect field is removed, and the template is found to be valid and the deployment succeeds. The PR for the change is here: #80 

![image](https://user-images.githubusercontent.com/58763328/91879334-9ca06780-ec9d-11ea-90bd-ab6febbc16a4.png)

The raw error is given below:
{
  "deploymentStatusCode": -1,
  "stage": 6,
  "expected": true,
  "error": {
    "message": "Deployment template parse failed: 'Could not find member 'delegatedRoleDefinitionIds' on object of type 'TemplateOutputParameter'. Path 'outputs.authorizations.delegatedRoleDefinitionIds', line 82, position 42.'."
  },
  "subscriptionId": "cb729363-8115-4333-ac0f-99e4b64d2634",
  "location": "eastus",
  "deploymentName": "Microsoft.Template-20200901215323",
  "details": {
    "code": "InvalidTemplate",
    "message": "Deployment template parse failed: 'Could not find member 'delegatedRoleDefinitionIds' on object of type 'TemplateOutputParameter'. Path 'outputs.authorizations.delegatedRoleDefinitionIds', line 82, position 42.'.",
    "additionalInfo": [
      {
        "type": "TemplateViolation",
        "info": {
          "lineNumber": 0,
          "linePosition": 0,
          "path": ""
        }
      }
    ]
  }
}

**Comment by shante665** [comment]
having the same error Azure Error: InvalidRequestContent
Message: The request content was invalid and could not be deserialized: 'Could not find member 'delegatedRoleDefinitionIds' on object of type 'TemplateOutputParameter'. Path 'properties.template.outputs.authorizations.delegatedRoleDefinitionIds', line 82, position 42.'.

Delegated role definitions didn't use to be compulsory in the template file. and even after adding delegatedRoleDefinitions still  have the same error

**Comment by hakashya** [comment]
> having the same error Azure Error: InvalidRequestContent
> Message: The request content was invalid and could not be deserialized: 'Could not find member 'delegatedRoleDefinitionIds' on object of type 'TemplateOutputParameter'. Path 'properties.template.outputs.authorizations.delegatedRoleDefinitionIds', line 82, position 42.'.
> 
> Delegated role definitions didn't use to be compulsory in the template file. and even after adding delegatedRoleDefinitions still have the same error

@shante665 If you're deploying the template to onboard a subscription, you can completely remove the delegatedRoleDefinitionIds part of the output to ensure it runs correctly.

**Comment by shante665** [comment]
@hakashya yes, i am trying to onboard a subscription. I had removed it from the parameters file, but the template file still had it and it threw the same error. I was going to avoid editing the template file itself. It's easy to break with json. I'll update the template file and try again

**Comment by shante665** [comment]
Okay I managed to not break the template file. removed the  "delegatedRoleDefinitionIds" from both the template and parameters files and it worked. thank you @hakashya

**Comment by hakashya** [comment]
The template has been corrected and merged into master.
