### ISSUE TITLE
Lighthouse Subscription Deployment fails

### ISSUE THREAD

**Issue by happy-jo** [Azure/Azure-Lighthouse-samples#89]
When deploying the [Azure Lighthouse for Subscription access](https://raw.githubusercontent.com/Azure/Azure-Lighthouse-samples/master/templates/delegated-resource-management/delegatedResourceManagement.json) I find that I'm still forced to select a  Resource group and the templated also fails with the following error.

![image](https://user-images.githubusercontent.com/16526141/95783748-7c05fd00-0ca0-11eb-82d5-04ec162cdb0c.png)

![image](https://user-images.githubusercontent.com/16526141/95783718-698bc380-0ca0-11eb-8241-987200d13c7e.png)

**Comment by serenaz** [comment]
The Azure Portal custom deployment/"deploy to Azure buttons" should have fixed this. Let us know if it's still an issue!
